version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: worknest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: worknest-app
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/worknest
      - JWT_SECRET=${JWT_SECRET:-change_this_secret}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: "http://localhost:3000/api"
    container_name: worknest-web
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  mongo-data:
